<?php

namespace AppBundle\Repository;

/**
 * GameEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
