<?php

namespace AppBundle\Repository;
use AppBundle\Entity\GameEntity;
use AppBundle\Entity\MoveEntity;

/**
 * MoveEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoveEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
